### ISSUE TITLE
Appservice won't create slackbot user

### ISSUE THREAD

**Issue by barudaret** [matrix-org/matrix-appservice-slack#125]
I'm trying to run this appservice on my own instance.  I'm following the readme's instructions.  The readme seems inadequate because of #86.  Following the readme, when it comes time to invite the slackbot to my admin control room, I find out that the slackbot account doesn't exist, which means the appservice isn't creating it.

When I launch the appservice, its console output looks like this: 
```
$ node app.js -c config.yaml -p 25566
Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
Mar-24 06:58:53.836 INFO app Matrix-side listening on port %s 25566
Mar-24 06:58:53.850 INFO SlackHookHandler Slack-side listening on port 9898 over http
Mar-24 06:58:53.907 INFO Main Loading teams.db

```

I don't know if it's *supposed* to progress beyond "Main Loading teams.db", but it never does.  I've left it running for days, and this is still the last thing it's spat out.  It might be hanging on something.  I have restarted both the appservice and synapse several times to no avail.  Anyway, I found out that if I invite the nonexistent MXID to a room despite it not existing, the appservice spits out this line on the console: ```Mar-24 06:59:12.936 INFO bridge ::1 - - [24/Mar/2019:06:59:12 +0000] "PUT /transactions/5?access_token=<REDACTED> HTTP/1.1" 200 55 "-" "Synapse/0.99.2"```

**Comment by olmari** [comment]
I can confirm I have this same issue when trying to make appservice-sclack work. No user created and pretty much exact same messages on logs.

**Comment by Half-Shot** [comment]
Sorry to hear about this, and how this has been open for so long :(. Can you share your config so I can see if there is any divergence from what we are running?

**Comment by barudaret** [comment]
```
slack_hook_port: 9898
inbound_uri_prefix: "https://ostavrosnika.com:9898/"
bot_username: "slackbot"
username_prefix: "slack_"

# Optional
#slack_master_token: "abc-123-def"

# Optional
matrix_admin_room: "!jGXPpRqagMWxWHzrcp:ostavrosnika.com"

homeserver:
  url: http://localhost:8008
  server_name: ostavrosnika.com

# Optional
#tls:
#  key_file: /path/to/tls.key
#  crt_file: /path/to/tls.crt
#
#logging:
#  console: "info"
#  files:
#      - "./debug.log": "info"
#      - "./error.log": "error"
```

**Comment by Half-Shot** [comment]
Hmm, looks sane. And the reg file?

**Comment by barudaret** [comment]
```
id: 😃
hs_token: 🤷‍♂️
as_token: 🔥
namespaces:
  users:
    - exclusive: true
      regex: '@slack_.*'
  aliases: []
  rooms: []
url: 'http://localhost:25566'
sender_localpart: slackbot
rate_limited: true
protocols: null
```

**Comment by kingoftheconnors** [comment]
I'm having the same problem. One thing I tried was to update my reg file because the aliases seemed off.
```
namespaces:
  users:
    - exclusive: true
      regex: '@slack_.*'
  aliases:
    - exclusive: true
      regex: '#slack_.*'
  rooms: []
```

Didn't work.
In all the problems I've found on the internet, the `Unable to load crypto module` was always irrelevant to the problem and the real problem was something else. Hmmmmm.
