### ISSUE TITLE
Need to include media_url for files M->S to work

### ISSUE THREAD

**Issue by olmari** [matrix-org/matrix-appservice-slack#139]
If self-hosted appservice-slack is on same server than synapse is, url in config is set to localhost:port, and when media is also bridged there needs to be `media_url` set in appservice config file like follows (in our server):

```
homeserver:
  media_url: https://matrix.hacklab.fi
  url: http://localhost:8008
  server_name: hacklab.fi
```

Without that slackbot gives media/picture-urls as `http://localhost:8008/.....` to slack which is obvious failure.. But defining `media_url` resolves this.

ADD/EDIT: So this is first and foremost an documentation issue only, reading source code revealed this is needed and already supported and so on.
