### ISSUE TITLE
Slack users are not synced to Matrix so you can't DM them from the Matrix side

### ISSUE THREAD

**Issue by jaller94** [matrix-org/matrix-appservice-slack#644]
Slack Team Sync for members should always be on and working according to these Team Sync config lines:
```yaml
team_sync:
  all:
    users: 
      # Automatically sync the entire slack team(s) to Matrix so you can invite them to a DM 
       enabled: true
```

There are a few reports of this not working, so it should be validated that the Team Sync works for users.
